name: Build PDF document

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'latex/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build PDF file
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: latex
          root_file: main.tex
          latexmk_shell_escape: true