name: Create PDF document

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'latex/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'latex/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build PDF file
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: latex
          root_file: main.tex
          latexmk_shell_escape: true

      - name: Store PDF
        uses: actions/upload-artifact@v3
        with:
          path: latex/main.pdf

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          mkdir -p pdf && cp latex/main.pdf pdf/main.pdf
          git add pdf/main.pdf
          git commit -m "Add pdf file" 
          
      - name: Push PDF
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        
